name: Test and Create PR

on:
  pull_request:  # Trigger workflow on pull request events

jobs:
  test:
   # runs-on: ubuntu-latest  # Specify runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout pull request code
      
      - name: Create Pull Request (if tests pass)
        uses: actions/checkout@v3  # Checkout code again (optional)
         # Only run if previous steps succeeded
        run: |
          gh pr create \
            -t "Automatic Pull Request (Tests Passed)" \
            -B main \
            -h ${{ github.sha }}  # Replace with your PR body and title 

          # Add labels or assignees as needed

