name: manual run

on: [push]


jobs:
  create-pr:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
     
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Automatic PR from"  # Customize title
          body: "This pull request was created automatically from commit"  # Customize body
          branch: "testPRauto"  # Branch to create PR from
          base: main  # Target branch for PR

          # Disable automatic merging (recommended)
          automerge: false
          # delete-branch: true  # Optional: Delete source branch after PR creation
