name: CI
on:
  push:
    branches: [ "!main" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: ["!main" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Automatic PR from ${{ github.sha }}"  # Customize title
          body: "This pull request was created automatically from commit ${{ github.sha }}"  # Customize body
          branch: "testPRauto"  # Branch to create PR from
          base: main  # Target branch for PR
      - uses: actions/checkout@v4

            
         
     

  
