name: manual run

on: 
 push:
    branches:
      - main


jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
     
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Automatic PR from"  # Customize title
          body: "This pull request was created automatically from commit"  # Customize body
          branch: testPRauto  # Branch to create PR from
          

          # Disable automatic merging ()
          
          # delete-branch: true  # Optional: Delete source branch after PR creation
