name: Demo to create automatic PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout pull request code

      - name: Check for Changes
        run: |
          git fetch origin main
          git diff --quiet HEAD origin/main
          if [ $? -eq 0 ]; then
            echo "No changes detected. Skipping PR creation."
            exit 0
          fi
          echo "Changes detected. Proceeding with PR creation."

      - name: Raise Pull Request
        uses: peter-evans/create-pull-request@v3  # Assuming this action is compatible with Node.js 20 (check for updates)
        with:
          title: "Automatic PR from ${{ github.sha }}"  # Customize title based on commit SHA
          body: "This pull request was created automatically."  # Customize body message
          branch: "auto-pr-branch"  # Branch name for the PR
          base: main  # Target branch for the PR
          token: ${{ secrets.GITHUB_TOKEN }}  # Access token with pull request creation permissions
          delete-branch: true  # Optional: Delete source branch after PR creation

          # Removed these lines (author and committer):
          # author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          # committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
